### PR TITLE
Move  response calculation to device.

### PR DESCRIPTION
**Pull request by zhihuadong**

### CODE REVIEW

**Comment by HaiwangYu** [comment]
Hi @zhihuadong Thanks for making this improvements. I encountered some issues with the CUDA backend and Kyle's v2.2 container. OMP backend also fails at around similar place. I am still investigating. Some suggestions would be very helpful though. Thanks.

```
Kokkos::Cuda::initialize WARNING: running kernels compiled for compute capability 7.0 on device with compute capability 7.5 , this will likely reduce potential performance.
Kokkos::initialized
[10:14:56.196] I [  wct   ] loading compressed json file: /home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-data/protodune-wires-larsoft-v4.json.bz2
[10:14:58.090] I [  wct   ] loading compressed json file: /home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-data/dune-garfield-1d565.json.bz2
p000 : 7.89878e-08
yuhw: get_charge_matrix_kokkos
npatches= 1
total patch size: 72 WeightStrat: 2
set_sampling_Time: 0.00245243
ScatterAdd_Time : 1.7057e-05
get_charge_matrix_kokkos(): Total_ScatterAdd_Time : 1.7057e-05
get_charge_matrix_kokkos(): Total_set_sampling_Time : 0.00245243
get_charge_matrix_kokkos() : m_fluctuate : 0
set_sampling(): part1 time : 0, part2 time : 0, part3 time : 0
[10:14:59.138] I [  sim   ] yuhw: pitch   5365 5765 400 224
[10:14:59.138] I [  sim   ] yuhw: start-end 537-577 1231-1455 40 224
[10:14:59.138] I [  sim   ] yuhw: m_num_group 11
WIRECELL_KOKKOSARRAY_CUDA
WIRECELL_KOKKOSARRAY_CUDA
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaMemcpy(dst, src, n, cudaMemcpyDefault) error( cudaErrorIllegalAddress): an illegal memory access was encountered /scratch/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:105
Traceback functionality not available


Thread 1 "wire-cell" received signal SIGABRT, Aborted.
0x00007ffff3add3d7 in raise () from /lib64/libc.so.6
(gdb) where
#0  0x00007ffff3add3d7 in raise () from /lib64/libc.so.6
#1  0x00007ffff3adeac8 in abort () from /lib64/libc.so.6
#2  0x00007ffff4644203 in __gnu_cxx::__verbose_terminate_handler () at ../../.././libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff464fc76 in __cxxabiv1::__terminate (handler=<optimized out>)
    at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff464fce1 in std::terminate () at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff464ff35 in __cxxabiv1::__cxa_throw (obj=obj@entry=0xbff9830, 
    tinfo=0x7ffff49772a0 <typeinfo for std::runtime_error>, dest=0x7ffff4665140 <std::runtime_error::~runtime_error()>)
    at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007fffa22563e7 in Kokkos::Impl::throw_runtime_exception (msg=...)
    at /scratch/kokkos/core/src/impl/Kokkos_Error.cpp:72
#7  0x00007fffa231d015 in Kokkos::Impl::cuda_internal_error_throw (e=cudaErrorIllegalAddress, name=<optimized out>, 
    file=<optimized out>, line=105) at /scratch/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp:154
#8  0x00007fffa23192f7 in Kokkos::Impl::SharedAllocationRecord<Kokkos::CudaSpace, void>::SharedAllocationRecord (
    this=0xc822fa0, arg_space=..., arg_label=..., arg_alloc_size=716800, 
    arg_dealloc=0x7fffa22e2290 <Kokkos::Impl::(anonymous namespace)::deallocate<Kokkos::CudaSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Cuda, Kokkos::complex<float>, false> >(Kokkos::Impl::SharedAllocationRecord<void, void>*)>)
    at /scratch/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp:534
#9  0x00007fffa22dc329 in Kokkos::Impl::SharedAllocationRecord<Kokkos::CudaSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Cuda, Kokkos::complex<float>, false> >::SharedAllocationRecord (arg_alloc=716800, arg_label=..., arg_space=..., 
    this=0xc822fa0) at /opt/kokkos-cuda/include/impl/Kokkos_SharedAlloc.hpp:343
#10 Kokkos::Impl::SharedAllocationRecord<Kokkos::CudaSpace, Kokkos::Impl::ViewValueFunctor<Kokkos::Cuda, Kokkos::complex<float>, false> >::allocate (arg_alloc=<optimized out>, arg_label=..., arg_space=...)
    at /opt/kokkos-cuda/include/impl/Kokkos_SharedAlloc.hpp:364
#11 Kokkos::Impl::ViewMapping<Kokkos::ViewTraits<Kokkos::complex<float>**, Kokkos::LayoutLeft, Kokkos::Cuda>, void>::allocate_shared<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Kokkos::Impl::WithoutInitializing_t, std::integral_constant<unsigned int, 0u>, Kokkos::CudaSpace, Kokkos::Cuda> (arg_layout=..., arg_layout=..., 
    arg_prop=..., this=0x7fffffff6508) at /opt/kokkos-cuda/include/impl/Kokkos_ViewMapping.hpp:3256
#12 Kokkos::View<Kokkos::complex<float>**, Kokkos::LayoutLeft, Kokkos::Cuda>::View<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Kokkos::Impl::WithoutInitializing_t>(Kokkos::Impl::ViewCtorProp<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Kokkos::Impl::WithoutInitializing_t> const&, std::enable_if<!Kokkos::Impl::ViewCtorProp<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Kokkos::Impl::WithoutInitializing_t>::has_pointer, Kokkos::LayoutLeft>::type const&) (arg_layout=..., arg_prop=..., this=0x7fffffff6500)
    at /opt/kokkos-cuda/include/Kokkos_View.hpp:1551
#13 Kokkos::View<Kokkos::complex<float>**, Kokkos::LayoutLeft, Kokkos::Cuda>::View<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Kokkos::Impl::WithoutInitializing_t>(Kokkos::Impl::ViewCtorProp<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Kokkos::Impl::WithoutInitializing_t> const&, std::enable_if<!Kokkos::Impl::ViewCtorProp<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Kokkos::Impl::WithoutInitializing_t>::has_pointer, unsigned long>::type, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long) (arg_N7=18446744073709551615, arg_N6=18446744073709551615, 
    arg_N5=18446744073709551615, arg_N4=18446744073709551615, arg_N3=18446744073709551615, arg_N2=18446744073709551615, 
    arg_N1=224, arg_N0=400, arg_prop=..., this=0x7fffffff6500) at /opt/kokkos-cuda/include/Kokkos_View.hpp:1603
#14 WireCell::KokkosArray::gen_2d_view<Kokkos::View<Kokkos::complex<float>**, Kokkos::LayoutLeft, Kokkos::Cuda> > (
    N0=N0@entry=400, N1=N1@entry=224, val=val@entry=0)
    at /home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos-test/.cmake-kokkos/../inc/WireCellGenKokkos/KokkosArray.h:49
#15 0x00007fffa22bf8a3 in WireCell::KokkosArray::dft_rc (dim=0, in=...)
    at /home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos-test/.cmake-kokkos/../inc/WireCellGenKokkos/KokkosArray_cu--Type <RET> for more, q to quit, c to continue without
--Type <RET> for more, q to quit, c to continue without paging--
da.h:43
#16 WireCell::GenKokkos::ImpactTransform::transform_matrix (this=this@entry=0x7fffffff6ca0) at /home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos-test/src/ImpactTransform.cxx:424
#17 0x00007fffa228fc5b in WireCell::GenKokkos::DepoTransform::operator() (this=<optimized out>, in=..., out=...) at /home/yuhw/wc/wct-analysis/csi-kokkos/wire-cell-gen-kokkos-test/src/DepoTransform.cxx:232
#18 0x00007ffff774dca2 in WireCell::IFunctionNode<WireCell::IDepoSet, WireCell::IFrame>::operator() (this=0x1092a40, anyin=..., anyout=...) at ../iface/inc/WireCellIface/IFunctionNode.h:43
#19 0x00007fffa06a3cce in WireCell::Pgraph::Function::operator() (this=0xc31cd30) at ../pgraph/inc/WireCellPgraph/Wrappers.h:154
#20 0x00007fffa06aa14c in WireCell::Pgraph::Graph::call_node (this=0x1093ef0, node=0xc31cd30) at ../pgraph/src/Graph.cxx:146
#21 0x00007fffa06ab389 in WireCell::Pgraph::Graph::execute (this=this@entry=0x1093ef0) at ../pgraph/src/Graph.cxx:116
#22 0x00007fffa06ae0ed in WireCell::Pgraph::Pgrapher::execute (this=0x1093ee0) at ../pgraph/src/Pgrapher.cxx:59
#23 0x00007ffff799edbd in WireCell::Main::operator() (this=this@entry=0x7fffffff75e0) at ../apps/src/Main.cxx:365
#24 0x0000000000408025 in main (argc=<optimized out>, argv=0x7fffffff7848) at ../apps/apps/wire-cell.cxx:22
```

**Comment by zhihuadong** [comment]
@HaiwangYu , Did you try on 2.1 container ? I kind of remember got similar error on 2.2 due to an 0 charge patch. But this Pr#27 should have a commit fixed it. It could be a different error too.

**Comment by brettviren** [comment]
Not enough GPU RAM?  Can you print `n` in GDB or  from the code to see what is given to the `cudaMemcpy()` function?

**Comment by zhihuadong** [comment]
I just tried 8a13e1c   on 2.2 container, and did not get error.

**Comment by HaiwangYu** [comment]
@zhihuadong, could you run this in the example folder:
```
wire-cell -l stdout -L info -c wct-sim-check.jsonnet
```

**Comment by zhihuadong** [comment]
Yes I do get the error , I check more

**Comment by zhihuadong** [comment]
0c45533 should fix the core dump caused by reduced response size not right.

**Pull request merged**
